name: APK-Datei bauen

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job-apk-bauen:
    name: Debug-APK bauen
    runs-on: ${{ matrix.betriebssystem }}
    strategy:
      matrix:
        java-version: ['17', '21']
        betriebssystem: ['ubuntu-latest', 'macos-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK für Java ${{ matrix.java-version }} einrichten
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Gradle mit Java ${{ matrix.java-version }} aufrufen
        run: bash ./gradlew clean assembleDebug --stacktrace
      - name: APK-Datei hochladen
        uses: actions/upload-artifact@v4
        with:
          name: ButtonEventHandler-Java${{ matrix.java-version }}-${{ matrix.betriebssystem }}-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 2


