name: APK-Datei bauen

on:
  push:
    branches:
      - master
  workflow_dispatch: # Button für manuelles Auslösen der Pipeline

jobs:
  job-apk-bauen-ubuntu:
    name: Debug-APK auf Ubuntu-Linux bauen
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['17', '21']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK für Java ${{ matrix.java-version }} einrichten
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Gradle mit Java ${{ matrix.java-version }} aufrufen
        run: bash ./gradlew clean assembleDebug --stacktrace
      - name: APK-Datei hochladen
        uses: actions/upload-artifact@v4
        with:
          name: ButtonEventHandler-Java${{ matrix.java-version }}-ubuntu-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 2

  job-apk-bauen-macos:
    name: Debug-APK auf MacOS bauen
    runs-on: macos-latest
    needs: job-apk-bauen-ubuntu
    strategy:
      matrix:
        java-version: ['17', '21']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK für Java ${{ matrix.java-version }} einrichten
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Gradle mit Java ${{ matrix.java-version }} aufrufen
        run: bash ./gradlew clean assembleDebug --stacktrace
      - name: APK-Datei hochladen
        uses: actions/upload-artifact@v4
        with:
          name: ButtonEventHandler-Java${{ matrix.java-version }}-macos-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 2



